version: '3'
services:

  app:
    tty: true
    container_name: rss_feed_app
    build:
      context: .
      dockerfile: Dockerfile.production
    image: rss_feed_app_1
    command: bash -c "npm run start"
    volumes:
      - ./log/:/app/log/
      - ./.env.production:/app/.env.production
      - ./database.production.sqlite:/app/database.production.sqlite
