version: '3'
services:

  rss_feed:
    tty: true
    container_name: rss_feed_app
    build:
      context: .
      dockerfile: Dockerfile.production
    image: rss_feed_app_1
    command: bash -c "npm run job:production"
    volumes:
      - ./:/app
